kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      
      additionalScrapeConfigs:
        - job_name: 'Interface PI'
          static_configs:
            - targets: ['10.77.152.90:8080']
          metrics_path: '/q/metrics'

        - job_name: 'Interface Participant'
          static_configs:
            - targets: ['interface-participant:8584']

        - job_name: 'RabbitMQ'
          static_configs:
            - targets: ['10.77.152.90:15692']

        - job_name: 'Node Exporter'
          static_configs:
            - targets: ['10.77.152.90:9100']

  additionalPrometheusRulesMap:
    custom-rules:
      groups:
        - name: AllInstances
          rules:
          - alert: Instance(s) tombée(s)
            expr: up == 0
            for: 1m
            annotations:
              title: "L'instance {{ `{{` }} $labels.instance {{ `}}` }} est tombée"
              description: "Le microservice {{ `{{` }} $labels.job {{ `}}` }} est tombé depuis plus d'une minute."
            labels:
              severity: 'critical'
              team: supervision

  alertmanager:
    config:
      route:
        group_by: ['AllInstances']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
        receiver: 'sms-webhook'
      receivers:
      - name: 'sms-webhook'
        webhook_configs:
        - url: 'http://interface-participant:4000/bo/alerts'
          send_resolved: true


  grafana:
    adminPassword: "admin"
    service:
      type: NodePort
      nodePort: 9003
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://observability-stack-loki:3100
        access: proxy
        editable: true
      - name: Tempo
        type: tempo
        url: http://observability-stack-tempo:3100
        access: proxy
        editable: true

loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
  promtail:
    enabled: true


tempo-stack:
  tempo:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi

opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-contrib
  mode: deployment
  replicaCount: 1

  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP

  service:
    type: NodePort
  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      otlp:
        endpoint: "observability-stack-tempo:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9464"
      otlphttp:
        endpoint: "http://observability-stack-loki:3100/otlp"
        encoding: json
        tls:
          insecure: true

    processors:
      batch: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
          processors: [batch]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
          processors: [batch]
        logs:
          receivers: [otlp]
          exporters: [otlphttp]
          processors: [batch]